// Avoid clippy warnings generated by tests that doesn't use every tests_extensions (since each test
// is a different compilation target).
#![allow(dead_code)]

pub mod fake;
pub mod mock;
mod routes;

use mithril_common::test_utils::TempDir;
use std::path::PathBuf;

pub fn get_test_dir(subdir_name: &str) -> PathBuf {
    TempDir::create("client_integration", subdir_name)
}

pub fn test_logger() -> slog::Logger {
    use slog::Drain;

    let decorator = slog_term::PlainDecorator::new(slog_term::TestStdoutWriter);
    let drain = slog_term::CompactFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();
    slog::Logger::root(std::sync::Arc::new(drain), slog::o!())
}
