services:
  cardano-node-signer-block-producer:
    volumes:
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/dmq/block-producer/ipc:/ipc-dmq
    environment:
      - DMQ_NODE_SOCKET_PATH=/ipc-dmq/dmq.socket
    depends_on:
      dmq-node-block-producer:
        condition: service_started
      dmq-node-relay:
        condition: service_started
