services:
  cardano-node-signer-relay:
    image: cardano-node/${CARDANO_IMAGE_ID}-modified
    container_name: cardano-node-relay-signer-${SIGNER_ID}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.cardano
      args:
        CARDANO_IMAGE_ID: ${CARDANO_IMAGE_ID}
        CARDANO_IMAGE_REGISTRY: ${CARDANO_IMAGE_REGISTRY}
    user: ${CURRENT_UID}
    profiles:
      - cardano
      - all
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/config/relay/${NETWORK}:/config
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/db/relay:/db
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/ipc:/ipc
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/pool:/pool
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/www:/www
    ports:
      - "${SIGNER_CARDANO_RELAY_PORT}:${SIGNER_CARDANO_RELAY_PORT}"
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/pool/topology-relay.json",
        "--database-path",
        "/db",
        "--port",
        "${SIGNER_CARDANO_RELAY_PORT}"
      ]

  cardano-node-signer-block-producer:
    image: cardano-node/${CARDANO_IMAGE_ID}-modified
    container_name: cardano-node-block-producer-signer-${SIGNER_ID}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.cardano
      args:
        CARDANO_IMAGE_ID: ${CARDANO_IMAGE_ID}
    user: ${CURRENT_UID}
    profiles:
      - cardano
      - all
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/config/block-producer/${NETWORK}:/config
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/db/block-producer:/db
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/ipc:/ipc
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/pool:/pool
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/www:/www
    ports:
      - "${SIGNER_CARDANO_BLOCK_PRODUCER_PORT}:${SIGNER_CARDANO_BLOCK_PRODUCER_PORT}"
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/pool/topology-block-producer.json",
        "--database-path",
        "/db",
        "--port",
        "${SIGNER_CARDANO_BLOCK_PRODUCER_PORT}",
        "--shelley-kes-key",
        "/pool/kes.skey",
        "--shelley-vrf-key",
        "/pool/vrf.skey",
        "--shelley-operational-certificate",
        "/pool/opcert.cert"
      ]

  mithril-signer:
    depends_on:
      cardano-node-signer-block-producer:
        condition: service_started
      cardano-node-signer-relay:
        condition: service_started
    environment:
      - DB_DIRECTORY=/mithril-signer-${SIGNER_ID}/cardano/db
    volumes:
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/db/block-producer:/mithril-signer-${SIGNER_ID}/cardano/db
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/pool:/mithril-signer-${SIGNER_ID}/cardano/pool
      - ../data/${NETWORK}/mithril-signer-${SIGNER_ID}/cardano/ipc:/ipc

networks:
  default:
    name: mithril_network
    external: true
