version: '3.6'

services:
  mithril-node-poc:
    container_name: mithril-node-poc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      MITHRIL_PARTY_ID: 1
      POSTGRES_DSN: "host=postgres port=5432 user=postgres password=mysecretpassword dbname=postgres sslmode=disable"
      HTTP_LISTEN_ADDR: "0.0.0.0:8000"
    depends_on:
      - "postgres"

  postgres:
    container_name: postgres
    image: postgres:alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: