use mithril_metric::{build_metrics_service, MetricsServiceExporter};

use mithril_metric::metric::{MetricCollector, MetricCounter};

// TODO Change help text to reflect the actual metric
build_metrics_service!(
    MetricsService,
    certificate_detail_total_served_since_startup:MetricCounter(
        "mithril_aggregator_certificate_detail_total_served_since_startup_counter",
        "certificate_detail_total_served_since_startup"
    ),
    artifact_cardano_db_total_served_since_startup:MetricCounter(
        "mithril_aggregator_artifact_cardano_db_total_served_since_startup_counter",
        "artifact_cardano_db_total_served_since_startup"
    ),
    artifact_mithril_stake_distribution_total_served_since_startup:MetricCounter(
        "mithril_aggregator_artifact_mithril_stake_distribution_total_served_since_startup_counter",
        "artifact_mithril_stake_distribution_total_served_since_startup"
    ),
    artifact_cardano_stake_distribution_total_served_since_startup:MetricCounter(
        "mithril_aggregator_artifact_cardano_stake_distribution_total_served_since_startup_counter",
        "artifact_cardano_stake_distribution_total_served_since_startup"
    ),
    artifact_cardano_transaction_total_served_since_startup:MetricCounter(
        "mithril_aggregator_artifact_cardano_transaction_total_served_since_startup_counter",
        "artifact_cardano_transaction_total_served_since_startup"
    ),
    proof_cardano_transaction_total_served_since_startup:MetricCounter(
        "mithril_aggregator_proof_cardano_transaction_total_served_since_startup_counter",
        "proof_cardano_transaction_total_served_since_startup"
    ),
    signer_registration_total_received_since_startup:MetricCounter(
        "mithril_aggregator_signer_registration_total_received_since_startup_counter",
        "signer_registration_total_received_since_startup"
    ),
    signature_registration_total_received_since_startup:MetricCounter(
        "mithril_aggregator_signature_registration_total_received_since_startup_counter",
        "signature_registration_total_received_since_startup"
    ),
    certificate_detail_total_produced_since_startup:MetricCounter(
        "mithril_aggregator_certificate_detail_total_produced_since_startup_counter",
        "certificate_detail_total_produced_since_startup"
    ),
    artifact_cardano_db_total_produced_since_startup:MetricCounter(
        "mithril_aggregator_artifact_cardano_db_total_produced_since_startup_counter",
        "artifact_cardano_db_total_produced_since_startup"
    ),
    artifact_mithril_stake_distribution_total_produced_since_startup:MetricCounter(
        "mithril_aggregator_artifact_mithril_stake_distribution_total_produced_since_startup_counter",
        "artifact_mithril_stake_distribution_total_produced_since_startup"
    ),
    artifact_cardano_stake_distribution_total_produced_since_startup:MetricCounter(
        "mithril_aggregator_artifact_cardano_stake_distribution_total_produced_since_startup_counter",
        "artifact_cardano_stake_distribution_total_produced_since_startup"
    ),
    artifact_cardano_transaction_total_produced_since_startup:MetricCounter(
        "mithril_aggregator_artifact_cardano_transaction_total_produced_since_startup_counter",
        "artifact_cardano_transaction_total_produced_since_startup"
    ),
    runtime_cycle_success_since_startup:MetricCounter(
        "mithril_aggregator_runtime_cycle_success_since_startup_counter",
        "runtime_cycle_success_since_startup"
    ),
    runtime_cycle_total_since_startup:MetricCounter(
        "mithril_aggregator_runtime_cycle_total_since_startup_counter",
        "runtime_cycle_total_since_startup"
    )

);
