[package]
name = "mithril-signer"
version = "0.1.0"
edition = "2021"
description = "A Mithril Signer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mithril-aggregator = { path = "../../mithril-network/mithril-aggregator" }
log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_debug"] }
clap = { version = "3.1.6", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
config = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "stream"] }
tar = "0.4.38"
flate2 = "1.0.23"

#[dev-dependencies]
mockall = "0.11.0"
httpmock = "0.6.6"
