[package]
name = "signature-network-node"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive", "env"] }
mithril-common = { path = "../../mithril-common", features = ["full"] }
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue", "serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
slog-scope = "4.4.0"
tokio = { version = "1.39.2", features = ["macros", "net", "rt", "rt-multi-thread"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
warp = "0.3.7"

[dev-dependencies]
