// Avoid clippy warnings generated by tests that doesn't use every tests_extensions (since each test
// is a different compilation target).
#![allow(dead_code)]

use blake2::{Blake2b, digest::consts::U32};

use mithril_stm::MembershipDigest;

pub mod protocol_phase;

#[derive(Clone, Debug)]
pub struct CustomMembershipDigest {}
impl MembershipDigest for CustomMembershipDigest {
    type ConcatenationHash = Blake2b<U32>;
    #[cfg(feature = "future_snark")]
    type SnarkHash = Blake2b<U32>;
}
