// Avoid clippy warnings generated by tests that doesn't use every tests_extensions (since each test
// is a different compilation target).
#![allow(dead_code)]

pub mod basic_verifier_tests;
pub mod protocol_phase;
