use anyhow::Context;
use midnight_zk_stdlib as zk;
use rand_chacha::ChaCha20Rng;
use rand_core::{CryptoRng, RngCore, SeedableRng};
use serde::{Deserialize, Serialize};

use crate::{
    MembershipDigest, Parameters, SingleSignature, StmResult, StmResult,
    circuits::halo2::circuit::StmCircuit,
    circuits::halo2::types::CircuitBase,
    proof_system::halo2_snark::prover_input::SnarkProverInput,
    proof_system::halo2_snark::{SNARK_PROOF_LENGTH, build_snark_message},
    protocol::SnarkError,
};

use super::{SnarkClerk, SnarkSetup};

/// `SnarkProof` contains a proof generated by the certificate circuit represented as a vector of
/// bytes. It can be verified using verifier parameters derived from the srs, the verification key
/// and the public inputs which are all public values
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnarkProof {
    /// Raw proof bytes produced by the SNARK prover.
    snark_proof: Vec<u8>,
}

// TODO: remove this allow dead_code directive when function is called or future_snark is activated
#[allow(dead_code)]
impl SnarkProof {
    /// Tries to generate a new SnarkProof given a vector of bytes as input
    /// The bytes only need to have the correct length as it is not possible
    /// to know if they represent a correct proof apart from verification
    ///
    /// Fails if the bytes have the wrong size (!= `SNARK_PROOF_LENGTH`)
    pub fn try_new(snark_proof: Vec<u8>) -> StmResult<Self> {
        if snark_proof.len() != SNARK_PROOF_LENGTH {
            return Err(SnarkError::ProofWithIncorrectSize(snark_proof.len()).into());
        }
        Ok(Self { snark_proof })
    }

    /// Verify a SNARK proof given a message, a merkle root and a
    /// snark setup
    ///
    /// Steps of the verification:
    /// 1. Generates the verifier parameters using the srs contained in the snark setup
    /// 2. Computes the public input of the circuit using the merkle root and message
    /// 3. Runs the verification of the proof
    ///
    /// This proofs verifies that there exists a witness such that:
    /// * each signatures in the witness is valid for the given message
    /// * each signatures has a winning lottery index
    /// * each leaf in the witness has a valid merkle path
    /// * each lottery index is unique and fits the parameters
    /// * enough lottery index are valid to meet the parameters requirements
    ///
    pub fn verify(
        &self,
        params: &Parameters,
        merkle_tree_depth: u32,
        message: &[u8],
        merkle_root: &[u8],
    ) -> StmResult<()> {
        let snark_setup = SnarkSetup::try_new(params, merkle_tree_depth)?;

        let verifier_parameters = snark_setup.srs.verifier_params();

        let proof_message = build_snark_message(merkle_root, message)?;
        let proof_instance = (proof_message[0].into(), proof_message[1].into());

        let verify_result = zk::verify::<StmCircuit, blake2b_simd::State>(
            &verifier_parameters,
            &snark_setup.verification_key,
            &proof_instance,
            None,
            &self.snark_proof,
        );

        if verify_result.is_ok() {
            Ok(())
        } else {
            Err(SnarkError::VerifyProofFail.into())
        }
    }

    /// Converts a SnarkProof to bytes by returning the proof bytes
    // TODO: write proper function
    pub fn to_bytes(&self) -> Vec<u8> {
        self.snark_proof.clone()
    }

    /// Deserialise a proof from raw bytes.
    pub fn from_bytes(bytes: &[u8]) -> StmResult<Self> {
        Self::try_new(bytes.to_vec())
    }
}

/// Holds the pre-computed SNARK setup and exposes proof generation.
///
/// The type parameter `R` selects the randomness source used during proof generation.
/// Use `try_new_non_deterministic` for production (`OsRng`) and `try_new_deterministic` for
/// reproducible tests.
// TODO: remove this allow dead_code directive when function is called or future_snark is activated
#[allow(dead_code)]
pub struct SnarkProver<R: RngCore + CryptoRng> {
    setup: SnarkSetup,
    rng: R,
}

// TODO: remove this allow dead_code directive when function is called or future_snark is activated
#[allow(dead_code)]
impl SnarkProver<rand_core::OsRng> {
    /// Create a new prover with a non-deterministic randomness source (`OsRng`).
    ///
    /// This is the constructor intended for production use.
    pub fn try_new_non_deterministic(
        parameters: &Parameters,
        merkle_tree_depth: u32,
    ) -> StmResult<Self> {
        Ok(Self {
            setup: SnarkSetup::try_new(parameters, merkle_tree_depth)
                .with_context(|| "Failed to initialize SNARK setup (SRS, circuit, keys)")?,
            rng: rand_core::OsRng,
        })
    }
}

// TODO: remove this allow dead_code directive when function is called or future_snark is activated
#[allow(dead_code)]
impl SnarkProver<ChaCha20Rng> {
    /// Create a new prover with a deterministic randomness source seeded from `seed`.
    ///
    /// This constructor is intended for testing, where reproducible proof generation is needed.
    pub fn try_new_deterministic(
        parameters: &Parameters,
        merkle_tree_depth: u32,
        seed: [u8; 32],
    ) -> StmResult<Self> {
        Ok(Self {
            setup: SnarkSetup::try_new(parameters, merkle_tree_depth)
                .with_context(|| "Failed to initialize SNARK setup (SRS, circuit, keys)")?,
            rng: ChaCha20Rng::from_seed(seed),
        })
    }
}

// TODO: remove this allow dead_code directive when function is called or future_snark is activated
#[allow(dead_code)]
impl<R: RngCore + CryptoRng> SnarkProver<R> {
    /// Aggregate a set of single signatures into a SNARK proof.
    ///
    /// Prepares the prover input (public instance and per-index witness) from the collected
    /// single signatures, then runs the SNARK prover.
    ///
    /// Returns an error if fewer than `k` valid signatures are available or if proof generation fails.
    pub fn aggregate_signatures<D: MembershipDigest>(
        &mut self,
        clerk: &SnarkClerk,
        signatures: &[SingleSignature],
        message: &[u8],
    ) -> StmResult<SnarkProof> {
        let snark_prover_input =
            SnarkProverInput::prepare_prover_input::<D>(clerk, signatures, message)
                .with_context(|| "Failed to prepare SNARK prover input")?;
        let instance = snark_prover_input.get_instance();
        let witness = snark_prover_input.into_witness();

        let snark_proof = zk::prove::<StmCircuit, PoseidonState<CircuitBase>>(
            &self.setup.srs,
            &self.setup.proving_key,
            &self.setup.circuit,
            &instance,
            witness,
            &mut self.rng,
        )
        .with_context(|| "SNARK proof generation failed")?;

        Ok(SnarkProof { snark_proof })
    }
}

#[cfg(feature = "future_snark")]
#[cfg(test)]
mod tests {
    use rand_chacha::ChaCha20Rng;
    use rand_core::{RngCore, SeedableRng};

    use crate::{
        Initializer, KeyRegistration, MidnightPoseidonDigest, MithrilMembershipDigest, Signer,
        SingleSignature,
        membership_commitment::MerkleTreeSnarkLeaf,
        proof_system::{SNARK_PROOF_LENGTH, SnarkClerk, halo2_snark::proof::SnarkProof},
    };

    use super::{Parameters, SnarkProver};

    type D = MithrilMembershipDigest;

    fn setup_signers_and_clerk(
        params: Parameters,
        nparties: usize,
        rng: &mut ChaCha20Rng,
    ) -> (Vec<Signer<D>>, SnarkClerk) {
        let mut key_reg = KeyRegistration::initialize();
        let mut initializers = Vec::with_capacity(nparties);

        for _ in 0..nparties {
            let init = Initializer::new(params, 1, rng);
            key_reg.register_by_entry(&init.clone().try_into().unwrap()).unwrap();
            initializers.push(init);
        }

        let closed_reg = key_reg.close_registration(&params).unwrap();
        let signers: Vec<Signer<D>> = initializers
            .into_iter()
            .map(|init| init.try_create_signer::<D>(&closed_reg).unwrap())
            .collect();

        let clerk = SnarkClerk::new_clerk_from_signer(&signers[0]);
        (signers, clerk)
    }

    fn collect_signatures(signers: &[Signer<D>], message: &[u8]) -> Vec<SingleSignature> {
        signers
            .iter()
            .filter_map(|signer| signer.create_single_signature(message).ok())
            .collect()
    }

    fn create_prover(
        params: Parameters,
        number_of_signers: usize,
        seed: [u8; 32],
    ) -> SnarkProver<ChaCha20Rng> {
        let merkle_tree_depth = number_of_signers.next_power_of_two().trailing_zeros();
        SnarkProver::try_new_deterministic(&params, merkle_tree_depth, seed).unwrap()
    }

    #[test]
    fn try_new_rejects_wrong_size() {
        // too short
        assert!(SnarkProof::try_new(vec![0u8; SNARK_PROOF_LENGTH - 1]).is_err());
        // too long
        assert!(SnarkProof::try_new(vec![0u8; SNARK_PROOF_LENGTH + 1]).is_err());
        // empty
        assert!(SnarkProof::try_new(vec![]).is_err());
    }

    #[test]
    fn try_new_accepts_correct_size() {
        assert!(SnarkProof::try_new(vec![0u8; SNARK_PROOF_LENGTH]).is_ok());
    }

    #[test]
    fn from_bytes_rejects_wrong_size() {
        assert!(SnarkProof::from_bytes(&[0u8; SNARK_PROOF_LENGTH - 1]).is_err());
        assert!(SnarkProof::from_bytes(&[0u8; SNARK_PROOF_LENGTH + 1]).is_err());
    }

    #[test]
    fn to_from_bytes_roundtrip() {
        let original = vec![42u8; SNARK_PROOF_LENGTH];
        let proof = SnarkProof::try_new(original.clone()).unwrap();
        assert_eq!(proof.to_bytes(), original);
        let recovered = SnarkProof::from_bytes(&proof.to_bytes()).unwrap();
        assert_eq!(recovered.to_bytes(), original);
    }

    #[test]
    fn produces_valid_snark_proof() {
        let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
        let params = Parameters {
            m: 200,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 10;
        let message = [1u8; 32];

        let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let signatures = collect_signatures(&signers, &message);
        let mut prover = create_prover(
            params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [0u8; 32],
        );

        let result = prover.aggregate_signatures::<D>(&clerk, &signatures, &message);
        assert!(
            result.is_ok(),
            "Expected proof creation to succeed, got: {result:?}"
        );

        let proof = result.unwrap();
        assert!(
            !proof.snark_proof.is_empty(),
            "Proof bytes should not be empty"
        );
    }

    #[test]
    fn fails_with_insufficient_signatures() {
        let mut rng = ChaCha20Rng::from_seed([1u8; 32]);
        let params = Parameters {
            m: 20,
            k: 5,
            phi_f: 0.1,
        };
        let nparties = 4;
        let message = [2u8; 32];

        let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let signatures = collect_signatures(&signers, &message);
        let mut prover = create_prover(
            params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [1u8; 32],
        );

        let result = prover.aggregate_signatures::<D>(&clerk, &signatures, &message);
        assert!(
            result.is_err(),
            "Expected failure due to insufficient signatures"
        );
    }

    #[test]
    fn fails_with_empty_signatures() {
        let mut rng = ChaCha20Rng::from_seed([2u8; 32]);
        let params = Parameters {
            m: 200,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 5;

        let (_, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let mut prover = create_prover(
            params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [2u8; 32],
        );

        let result = prover.aggregate_signatures::<D>(&clerk, &[], &[3u8; 32]);
        assert!(result.is_err(), "Expected failure with empty signatures");
    }

    #[test]
    fn correct_proof_verifies() {
        let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
        let params = Parameters {
            m: 200,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 10;
        let message = [1u8; 32];
        let merkle_tree_depth = (nparties as u32).next_power_of_two().trailing_zeros();

        let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let signatures = collect_signatures(&signers, &message);
        let root = clerk
            .closed_key_registration
            .to_merkle_tree::<MidnightPoseidonDigest, MerkleTreeSnarkLeaf>()
            .to_merkle_tree_commitment()
            .root;

        let mut prover = create_prover(
            params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [0u8; 32],
        );

        let result = prover.aggregate_signatures::<D>(&clerk, &signatures, &message);
        assert!(
            result.is_ok(),
            "Expected proof creation to succeed, got: {result:?}"
        );

        let snark_proof = result.unwrap();
        let result = snark_proof.verify(&params, merkle_tree_depth, message.as_slice(), &root);

        assert!(result.is_ok());
    }

    #[test]
    fn different_parameters_prove_and_verify_fails() {
        let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
        let params = Parameters {
            m: 100,
            k: 5,
            phi_f: 0.8,
        };
        let forged_params = Parameters {
            m: 3000,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 10;
        let message = [1u8; 32];
        let merkle_tree_depth = (nparties as u32).next_power_of_two().trailing_zeros();

        let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let signatures = collect_signatures(&signers, &message);
        let root = clerk
            .closed_key_registration
            .to_merkle_tree::<MidnightPoseidonDigest, MerkleTreeSnarkLeaf>()
            .to_merkle_tree_commitment()
            .root;

        let mut prover = create_prover(
            forged_params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [0u8; 32],
        );

        let result = prover.aggregate_signatures::<D>(&clerk, &signatures, &message);
        assert!(
            result.is_ok(),
            "Expected proof creation to succeed, got: {result:?}"
        );

        let snark_proof = result.unwrap();
        let result = snark_proof.verify(&params, merkle_tree_depth, message.as_slice(), &root);

        assert!(result.is_err());
    }

    #[test]
    fn verify_fails_with_random_bytes() {
        let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
        let params = Parameters {
            m: 100,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 10;
        let message = [1u8; 32];
        let merkle_tree_depth = (nparties as u32).next_power_of_two().trailing_zeros();

        let (_, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let root = clerk
            .closed_key_registration
            .to_merkle_tree::<MidnightPoseidonDigest, MerkleTreeSnarkLeaf>()
            .to_merkle_tree_commitment()
            .root;

        let mut random_bytes = vec![0u8; SNARK_PROOF_LENGTH];
        rng.fill_bytes(&mut random_bytes);
        let random_proof = SnarkProof::try_new(random_bytes).unwrap();
        let result = random_proof.verify(&params, merkle_tree_depth, message.as_slice(), &root);

        assert!(
            result.is_err(),
            "Expected verification of tampered proof to fail"
        );
    }

    #[test]
    fn verify_fails_with_wrong_message() {
        let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
        let params = Parameters {
            m: 100,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 10;
        let message = [1u8; 32];
        let wrong_message = [2u8; 32];
        let merkle_tree_depth = (nparties as u32).next_power_of_two().trailing_zeros();
        let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let signatures = collect_signatures(&signers, &message);
        let root = clerk
            .closed_key_registration
            .to_merkle_tree::<MidnightPoseidonDigest, MerkleTreeSnarkLeaf>()
            .to_merkle_tree_commitment()
            .root;
        let mut prover = create_prover(
            params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [0u8; 32],
        );

        let snark_proof = prover
            .aggregate_signatures::<D>(&clerk, &signatures, &message)
            .unwrap();
        let result =
            snark_proof.verify(&params, merkle_tree_depth, wrong_message.as_slice(), &root);

        assert!(result.is_err());
    }

    #[test]
    fn non_deterministic_proofs_verify() {
        let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
        let params = Parameters {
            m: 100,
            k: 5,
            phi_f: 0.8,
        };
        let nparties = 10;
        let merkle_tree_depth = (nparties as u32).next_power_of_two().trailing_zeros();
        let message = [1u8; 32];
        let (signers, clerk) = setup_signers_and_clerk(params, nparties, &mut rng);
        let signatures = collect_signatures(&signers, &message);
        let root = clerk
            .closed_key_registration
            .to_merkle_tree::<MidnightPoseidonDigest, MerkleTreeSnarkLeaf>()
            .to_merkle_tree_commitment()
            .root;

        let mut prover_1 = create_prover(
            params,
            clerk.closed_key_registration.number_of_registered_parties(),
            [0u8; 32],
        );

        let snark_proof_1 = prover_1
            .aggregate_signatures::<D>(&clerk, &signatures, &message)
            .unwrap();
        let snark_proof_2 = prover_1
            .aggregate_signatures::<D>(&clerk, &signatures, &message)
            .unwrap();

        assert!(
            snark_proof_1
                .verify(&params, merkle_tree_depth, &message, &root)
                .is_ok()
        );
        assert!(
            snark_proof_2
                .verify(&params, merkle_tree_depth, &message, &root)
                .is_ok()
        );

        assert!(
            snark_proof_1.snark_proof != snark_proof_2.snark_proof,
            "The two proofs are different but both verify."
        );
    }
}
