name: Manual crates publication

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: |
          SHA of the commit on which the mithril crates should be obtained.
        required: true
        type: string
      package:
        description: |
          Packages(s) to be published to crates.io registry.
        required: true
        type: choice
        options:
          - all
          - mithril-stm
          - mithril-common
          - mithril-client
          - mithril-build-script
          - mithril-cardano-node-internal-database
      dry_run:
        description: Dry run will not publish to crates.io registry.
        required: true
        type: boolean
        default: true

jobs:
  publish-crate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        if: inputs.package == matrix.package || inputs.package == 'all'
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Install stable toolchain
        if: inputs.package == matrix.package || inputs.package == 'all'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: ${{ inputs.dry_run && 'Test publish' || 'Publish' }} package to crates.io
        if: inputs.package == matrix.package || inputs.package == 'all'
        uses: ./.github/workflows/actions/publish-rust-crates
        with:
          dry_run: ${{ inputs.dry_run }}
          packages: mithril-stm, mithril-build-script, mithril-common, mithril-aggregator-client, mithril-aggregator-discovery, mithril-cardano-node-internal-database, mithril-client
          api_token: ${{ secrets.CRATES_IO_API_TOKEN }}
